project_id = "munrveyxpveqhijpcjjw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "https://munrveyxpveqhijpcjjw.supabase.co/auth/v1"
additional_redirect_urls = ["https://munrveyxpveqhijpcjjw.supabase.co"]

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[edge_functions]
enabled = true
port = 54323

[functions.generate-flashcards]
verify_jwt = false

[storage]
enabled = true
port = 54325
image_transformation = {enabled = true}

[inbucket]
enabled = true
port = 54326
smtp_port = 54327
pop3_port = 54328

[realtime]
enabled = true
port = 54329

[studio]
enabled = true
port = 54320

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100